



/* 	MERCI DE RESPECTER LES DOSSIERS
MERCI DE RESPECTER LA NOMANCLATURE
MERCI DE DEMANDER AVANT DE COMMENCER SI VOUS ETES PAS SUR
MERCI DE VOUS METTRE D'ACCORD AVEC VOTRE PARTENAIRE (GRAPHS ET SCRIPTS)MERCI DE M'AVOIR LU !
DES BIZOUS !





SIGNATURES :
QT --LU--
LIZA
CHLOE
LUCAS
*/